### ISSUE TITLE
Implement IEC IEV document layout

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-native-pdf#118]
Preview: https://webstore.iec.ch/preview/info_iec60050-171%7Bed1.0%7Db.pdf

Metanorma AsciiDoc document at https://github.com/glossarist/iev-document

**Comment by Intelligent2013** [comment]
@ronaldtse Could you provide an XML source file, please?
I can't make it on my Ubuntu due Ruby version conflict, and don't know how to solve it. Thank you,

**Comment by Intelligent2013** [comment]
@ronaldtse Is this task relevant?

**Comment by ronaldtse** [comment]
@Intelligent2013 yes! Sorry will provide sample shortly.

**Comment by Intelligent2013** [comment]
@ronaldtse I'm trying to generate xml file (os Ubuntu, the command `make all`) for https://github.com/glossarist/iev-document and the process ends with the error:
```
make sources/data
make[1]: Entering directory '/home/intluser/iev-document'
make[1]: 'sources/data' is up to date.
make[1]: Leaving directory '/home/intluser/iev-document'
make documents.html
make[1]: Entering directory '/home/intluser/iev-document'
bundle install --jobs 4 --retry 3
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
installing your bundle as root will break this application for all non-root
users on this machine.
Fetching https://github.com/metanorma/metanorma-iec
Fetching gem metadata from https://rubygems.org/...............
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies.........
Using rake 13.0.6
Using public_suffix 4.0.6
Using asciimath 2.0.2
Using htmlentities 4.3.4
Using mini_portile2 2.5.3
Using racc 1.5.2
Using rsec 1.0.0
Using latex-decode 0.3.2
Using bundler 2.1.4
Using camertron-eprun 1.1.1
Using cldr-plurals-runtime-rb 1.1.0
Using cliver 0.3.2
Using cnccs 0.1.6
Using coderay 1.1.3
Using concurrent-ruby 1.1.9
Using connection_pool 2.2.5
Using descriptive_statistics 2.5.1
Using unf_ext 0.0.7.7
Using ffi 1.15.3
Using ruby-ole 1.2.12.2
Using rubyzip 2.3.2
Using seven_zip_ruby 1.3.0
Using thor 1.0.1
Fetching rice 3.0.0
Using cabin 0.9.0
Using faraday-em_http 1.0.0
Using faraday-em_synchrony 1.0.0
Using faraday-excon 1.1.0
Using faraday-httpclient 1.0.1
Using faraday-net_http 1.0.1
Using faraday-net_http_persistent 1.2.0
Using faraday-patron 1.0.0
Using multipart-post 2.1.1
Using ruby2_keywords 0.0.5
Using rchardet 1.8.0
Using ttfunk 1.7.0
Using gb-agencies 0.0.7
Using hashie 4.1.0
Using hollaback 0.1.0
Using image_size 2.1.1
Using mime-types-data 3.2021.0704
Using plane1converter 0.0.1
Using thread_safe 0.3.6
Using uuidtools 2.2.0
Using iso-639 0.3.5
Using iso639 1.3.2
Using liquid 4.0.3
Using marcel 1.0.1
Using mn2pdf 1.34
Using method_source 1.0.0
Using net-http-digest_auth 1.4.1
Using rubyntlm 0.6.3
Using webrick 1.7.0
Using webrobots 0.1.2
Using multi_json 1.15.0
Using isoics 0.1.9
Using roman-numerals 0.3.0
Using ox 2.14.5
Using parslet 2.0.0
Using rexml 3.2.5
Using optout 0.0.2
Using unicode2latex 0.0.4
Using mnconvert 1.8.0
Using tokenizer 0.3.0
Using open-uri 0.1.0
Using socksify 1.7.1
Using addressable 2.8.0
Using nokogiri 1.11.7 (x86_64-linux)
Using bibtex-ruby 6.0.0
Using unf 0.1.4
Using ffi-libarchive 1.0.17
Using ffi-compiler2 2.0.1
Using net-http-persistent 4.0.1
Using tzinfo 2.0.4
Using sys-proctable 1.2.6
Using arr-pm 0.0.11
Using faraday 1.5.1
Using git 1.9.1
Using mime-types 3.3.1
Using pry 0.14.1
Using thor-hollaback 0.2.0
Using latexmath 0.1.5
Using ruby-graphviz 1.2.5
Using ruby-jing 0.0.1
Using asciimath2unitsml 0.3.3
Using css_parser 1.9.0
Using domain_name 0.5.20190701
Using down 5.2.2
Using ffi-libarchive-binary 0.2.4 (x86_64-linux)
Using libmspack 0.10.1
Using iev 0.2.5
Using sterile 1.0.23
Using relaton-bib 1.8.2
Using twitter_cldr 6.7.0
Using mathml2asciimath 0.0.11
Using nokogiri-styles 0.1.2
Using reverse_markdown 1.4.0
Using tzinfo-data 1.2021.1
Using faraday_middleware 1.0.0
Using html2doc 1.1.3
Using http-cookie 1.0.4
Using lutaml-uml 0.4.1
Using premailer 1.11.1
Using excavate 0.2.4
Using relaton-iso-bib 1.8.1
Using relaton-calconnect 1.8.0
Using relaton-cie 1.8.0
Using relaton-ecma 1.8.0
Using relaton-ieee 1.8.0
Using relaton-ietf 1.8.0
Using relaton-iho 1.8.0
Using relaton-nist 1.8.0
Using relaton-omg 1.8.0
Using relaton-w3c 1.8.0
Using fontist 1.10.0
Using mechanize 2.8.1
Using serrano 1.0.0
Using relaton-gb 1.8.1
Using relaton-iec 1.8.0
Using relaton-iso 1.8.0
Using relaton-ogc 1.8.0
Using relaton-un 1.8.0
Using lutaml-xmi 0.2.1
Using word-to-markdown 1.1.8
Using relaton-bipm 1.8.2
Using relaton-bsi 1.8.4
Using relaton-cen 1.8.pre1
Using relaton-itu 1.8.2
Using asciidoctor 2.0.15
Installing rice 3.0.0 with native extensions
Using metanorma-utils 1.2.3
Using reverse_adoc 0.3.3
Using relaton 1.8.1
Using metanorma 1.3.7
Using relaton-iev 1.1.2
Using relaton-cli 1.8.0
Using isodoc 1.7.1
Using metanorma-plugin-datastruct 0.1.4
Fetching expressir 1.0.0 (x86_64-linux)
Installing expressir 1.0.0 (x86_64-linux)
Fetching lutaml-express 0.2.0
Installing lutaml-express 0.2.0
Fetching lutaml 0.7.4
Installing lutaml 0.7.4
Fetching metanorma-plugin-lutaml 0.4.2
Installing metanorma-plugin-lutaml 0.4.2
Fetching metanorma-standoc 1.10.2
Installing metanorma-standoc 1.10.2
Fetching metanorma-generic 1.10.2
Fetching metanorma-iso 1.9.0.1
Fetching metanorma-ietf 2.3.6
Installing metanorma-ietf 2.3.6
Installing metanorma-generic 1.10.2
Fetching metanorma-ogc 1.3.7
Fetching metanorma-itu 1.3.7
Installing metanorma-iso 1.9.0.1
Fetching metanorma-un 0.6.7
Installing metanorma-itu 1.3.7
Fetching metanorma-cc 1.7.7
Installing metanorma-un 0.6.7
Installing metanorma-cc 1.7.7
Fetching metanorma-csa 1.8.7
Fetching metanorma-iho 0.3.7
Installing metanorma-csa 1.8.7
Fetching metanorma-m3aawg 1.7.7
Installing metanorma-iho 0.3.7
Fetching metanorma-bipm 1.1.5.1
Installing metanorma-m3aawg 1.7.7
Using metanorma-iec 1.3.7 from https://github.com/metanorma/metanorma-iec (at main@38a8e10)
Installing metanorma-bipm 1.1.5.1
Installing metanorma-ogc 1.3.7
Fetching metanorma-cli 1.4.12
Installing metanorma-cli 1.4.12
Bundle complete! 2 Gemfile dependencies, 155 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
mkdir -p documents
scripts/split_codes.rb sources/data/concept-1921303.yaml sources/data/concept-1921303.adoc
scripts/split_codes.rb sources/data/concept-1921308.yaml sources/data/concept-1921308.adoc
scripts/split_codes.rb sources/data/concept-1920620.yaml sources/data/concept-1920620.adoc
scripts/split_codes.rb sources/data/concept-1920116.yaml sources/data/concept-1920116.adoc
...
BUILT_TARGET=""; \
if [ "$BUILT_TARGET" = "" ] || [ "$BUILT_TARGET" = "null" ]; then \
	BUILT_TARGET=sources/iec-60050-192.xml; \
	echo "Running locally..."; bundle exec metanorma -x xml "${BUILT_TARGET//xml/adoc}"; \
else \
	if [ -f "$BUILT_TARGET" ] && [ "${BUILT_TARGET##*.}" == "xml" ]; then \
		cp "$BUILT_TARGET" sources/iec-60050-192.xml; \
	else \
		echo "Running locally..."; bundle exec metanorma -x xml $BUILT_TARGET; \
		cp "${BUILT_TARGET//adoc/xml}" sources/iec-60050-192.xml; \
	fi \
fi
Running locally...
/var/lib/gems/2.7.0/gems/metanorma-ietf-2.3.6/lib/asciidoctor/ietf/converter.rb:123: warning: already initialized constant Asciidoctor::Ietf::Converter::BCP_KEYWORDS
/var/lib/gems/2.7.0/gems/metanorma-ietf-2.3.6/lib/asciidoctor/ietf/cleanup.rb:11: warning: previous definition of BCP_KEYWORDS was here
[relaton] Info: detecting backends:
Traceback (most recent call last):
	47: from /usr/local/bin/metanorma:23:in `<main>'
	46: from /usr/local/bin/metanorma:23:in `load'
	45: from /var/lib/gems/2.7.0/gems/metanorma-cli-1.4.12/exe/metanorma:35:in `<top (required)>'
	44: from /var/lib/gems/2.7.0/gems/metanorma-cli-1.4.12/exe/metanorma:22:in `block in <top (required)>'
	43: from /var/lib/gems/2.7.0/gems/metanorma-cli-1.4.12/lib/metanorma/cli.rb:34:in `start'
	42: from /usr/lib/ruby/vendor_ruby/thor/base.rb:444:in `start'
	41: from /usr/lib/ruby/vendor_ruby/thor.rb:369:in `dispatch'
	40: from /usr/lib/ruby/vendor_ruby/thor/invocation.rb:126:in `invoke_command'
	39: from /var/lib/gems/2.7.0/gems/thor-hollaback-0.2.0/lib/thor/hollaback.rb:62:in `run'
	38: from /usr/lib/ruby/vendor_ruby/thor/command.rb:27:in `run'
	37: from /var/lib/gems/2.7.0/gems/metanorma-cli-1.4.12/lib/metanorma/cli/command.rb:45:in `compile'
	36: from /var/lib/gems/2.7.0/gems/metanorma-cli-1.4.12/lib/metanorma/cli/command.rb:45:in `each'
	35: from /var/lib/gems/2.7.0/gems/metanorma-cli-1.4.12/lib/metanorma/cli/command.rb:45:in `block in compile'
	34: from /var/lib/gems/2.7.0/gems/metanorma-cli-1.4.12/lib/metanorma/cli/command.rb:210:in `compile_document'
	33: from /var/lib/gems/2.7.0/gems/metanorma-cli-1.4.12/lib/metanorma/cli/compiler.rb:35:in `compile'
	32: from /var/lib/gems/2.7.0/gems/metanorma-cli-1.4.12/lib/metanorma/cli/compiler.rb:30:in `compile'
	31: from /var/lib/gems/2.7.0/gems/metanorma-cli-1.4.12/lib/metanorma/cli/compiler.rb:45:in `compile_file'
	30: from /var/lib/gems/2.7.0/gems/metanorma-1.3.7/lib/metanorma/compile.rb:27:in `compile'
	29: from /var/lib/gems/2.7.0/gems/metanorma-1.3.7/lib/metanorma/compile.rb:96:in `process_input'
	28: from /var/lib/gems/2.7.0/gems/metanorma-1.3.7/lib/metanorma/processor.rb:24:in `input_to_isodoc'
	27: from /var/lib/gems/2.7.0/gems/metanorma-1.3.7/lib/metanorma/input/asciidoc.rb:18:in `process'
	26: from /var/lib/gems/2.7.0/gems/asciidoctor-2.0.15/lib/asciidoctor/convert.rb:119:in `convert'
	25: from /var/lib/gems/2.7.0/gems/asciidoctor-2.0.15/lib/asciidoctor/document.rb:944:in `convert'
	24: from /var/lib/gems/2.7.0/gems/metanorma-standoc-1.10.2/lib/asciidoctor/standoc/utils.rb:13:in `convert'
	23: from /var/lib/gems/2.7.0/gems/metanorma-standoc-1.10.2/lib/asciidoctor/standoc/base.rb:163:in `document'
	22: from /var/lib/gems/2.7.0/gems/metanorma-standoc-1.10.2/lib/asciidoctor/standoc/base.rb:197:in `makexml'
	21: from /var/lib/gems/2.7.0/gems/metanorma-standoc-1.10.2/lib/asciidoctor/standoc/base.rb:189:in `makexml1'
	20: from /var/lib/gems/2.7.0/gems/metanorma-standoc-1.10.2/lib/asciidoctor/standoc/base.rb:171:in `version'
	19: from /var/lib/gems/2.7.0/gems/metanorma-standoc-1.10.2/lib/metanorma/standoc/version.rb:16:in `versioned'
	18: from /var/lib/gems/2.7.0/gems/metanorma-standoc-1.10.2/lib/metanorma/standoc/version.rb:12:in `all_modules'
	17: from /var/lib/gems/2.7.0/gems/metanorma-standoc-1.10.2/lib/metanorma/standoc/version.rb:12:in `flat_map'
	16: from /var/lib/gems/2.7.0/gems/metanorma-standoc-1.10.2/lib/metanorma/standoc/version.rb:12:in `each'
	15: from /var/lib/gems/2.7.0/gems/metanorma-standoc-1.10.2/lib/metanorma/standoc/version.rb:12:in `block in all_modules'
	14: from /var/lib/gems/2.7.0/gems/metanorma-standoc-1.10.2/lib/metanorma/standoc/version.rb:12:in `all_modules'
	13: from /var/lib/gems/2.7.0/gems/metanorma-standoc-1.10.2/lib/metanorma/standoc/version.rb:12:in `flat_map'
	12: from /var/lib/gems/2.7.0/gems/metanorma-standoc-1.10.2/lib/metanorma/standoc/version.rb:12:in `each'
	11: from /var/lib/gems/2.7.0/gems/metanorma-standoc-1.10.2/lib/metanorma/standoc/version.rb:12:in `block in all_modules'
	10: from /var/lib/gems/2.7.0/gems/metanorma-standoc-1.10.2/lib/metanorma/standoc/version.rb:10:in `all_modules'
	 9: from /var/lib/gems/2.7.0/gems/metanorma-standoc-1.10.2/lib/metanorma/standoc/version.rb:10:in `map'
	 8: from /var/lib/gems/2.7.0/gems/metanorma-standoc-1.10.2/lib/metanorma/standoc/version.rb:10:in `block in all_modules'
	 7: from /var/lib/gems/2.7.0/gems/metanorma-standoc-1.10.2/lib/metanorma/standoc/version.rb:10:in `const_get'
	 6: from /var/lib/gems/2.7.0/gems/metanorma-standoc-1.10.2/lib/metanorma/standoc/version.rb:10:in `require'
	 5: from /var/lib/gems/2.7.0/gems/thor-1.0.1/lib/thor/group.rb:1:in `<top (required)>'
	 4: from /var/lib/gems/2.7.0/gems/thor-1.0.1/lib/thor/group.rb:1:in `require_relative'
	 3: from /var/lib/gems/2.7.0/gems/thor-1.0.1/lib/thor/base.rb:1:in `<top (required)>'
	 2: from /var/lib/gems/2.7.0/gems/thor-1.0.1/lib/thor/base.rb:1:in `require_relative'
	 1: from /var/lib/gems/2.7.0/gems/thor-1.0.1/lib/thor/command.rb:1:in `<top (required)>'
/var/lib/gems/2.7.0/gems/thor-1.0.1/lib/thor/command.rb:2:in `<class:Thor>': superclass mismatch for class Command (TypeError)
make[1]: *** [Makefile:88: sources/iec-60050-192.xml] Error 1
rm sources/data/concept-1921204.adoc sources/data/concept-1920926.adoc sources/data/concept-1920412.adoc sources/data/concept-1920214.adoc sources/data/concept-1920505.adoc sources/data/concept-1920606.adoc sources/data/concept-1920707.adoc sources/data/concept-1920806.adoc sources/data/concept-1920906.adoc sources/data/concept-1921018.adoc sources/data/concept-1921007.adoc
...
make[1]: Leaving directory '/home/intluser/iev-document'
make: *** [Makefile:61: all] Error 2
```

I don't figure out what is the reason of it...
Is iev-document generating successfully  in your environment?

**Comment by ronaldtse** [comment]
It's running the wrong flavor (ietf) instead of (iec). That repo probably needs updating.

**Comment by Intelligent2013** [comment]
Done in https://github.com/glossarist/iev-document/issues/22.
