### ISSUE TITLE
ISO 10303-104 PDF generation error

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/mn-native-pdf#148]
Error 'StackOverflowError':
```
Exception in thread "main" java.lang.StackOverflowError
	at org.apache.xpath.XPathContext.getCurrentNodeList(XPathContext.java:1018)
	at org.apache.xpath.functions.FuncCurrent.execute(FuncCurrent.java:55)
	at org.apache.xpath.axes.FilterExprIteratorSimple.executeFilterExpr(FilterExprIteratorSimple.java:123)
	at org.apache.xpath.axes.FilterExprWalker.setRoot(FilterExprWalker.java:131)
	at org.apache.xpath.axes.WalkingIterator.setRoot(WalkingIterator.java:157)
	at org.apache.xpath.axes.NodeSequence.setRoot(NodeSequence.java:265)
	at org.apache.xpath.axes.LocPathIterator.asIterator(LocPathIterator.java:269)
```

occurs when xslt process the big table in `<annex id="annex-short-names-of-entities"`. Here in common.xsl:
```
<xsl:template match="*[local-name()='th'] | *[local-name()='td']" mode="simple-table-colspan">
		<xsl:choose>
			<xsl:when test="@colspan">
				<xsl:variable name="td">
					<xsl:element name="td">
						<xsl:attribute name="divide"><xsl:value-of select="@colspan"/></xsl:attribute>
						<xsl:apply-templates select="@*" mode="simple-table-colspan"/>
						<xsl:apply-templates mode="simple-table-colspan"/>
					</xsl:element>
				</xsl:variable>
				<xsl:call-template name="repeatNode">
					<xsl:with-param name="count" select="@colspan"/>
					<xsl:with-param name="node" select="$td"/>
				</xsl:call-template>
			</xsl:when>
			<xsl:otherwise>
				<xsl:element name="td">
					<xsl:apply-templates select="@*" mode="simple-table-colspan"/>
					<xsl:apply-templates mode="simple-table-colspan"/>
				</xsl:element>
			</xsl:otherwise>
		</xsl:choose>
	</xsl:template>
```

**Comment by Intelligent2013** [comment]
'StackOverflowError' error should be solved by adding jvm option `-Xss5m`:
`java -Xss5m -jar ... mn2pdf.jar`

But new bug occurs:
```
javax.xml.transform.TransformerException: org.xml.sax.SAXParseException; lineNumber: 5470; columnNumber: 19; Character reference "&#55349" is an invalid XML character.
	at org.apache.xalan.transformer.TransformerIdentityImpl.transform(TransformerIdentityImpl.java:502)
	at com.metanorma.fop.mn2pdf.convertmn2pdf(mn2pdf.java:149)
	at com.metanorma.fop.mn2pdf.main(mn2pdf.java:204)
Caused by: org.xml.sax.SAXParseException; lineNumber: 5470; columnNumber: 19; Character reference "&#55349" is an invalid XML character.
	at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLScanner.scanCharReferenceValue(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xalan.transformer.TransformerIdentityImpl.transform(TransformerIdentityImpl.java:485)
	... 2 more

```

Note - lineNumber: 5470 - is a line number in temporary .fo file, not source xml file.

**Comment by Intelligent2013** [comment]
One more issue:
`ряЁ 28, 2020 9:07:10 PM net.sourceforge.jeuclid.elements.support.attributes.MathVariant createFont                                          WARNING: No font available to display character d835                                                                                        ряЁ 28, 2020 9:07:10 PM net.sourceforge.jeuclid.elements.support.attributes.MathVariant createFont                                          INFO: Find a font at  http://www.fileformat.info/info/unicode/char/d835/fontsupport.htm or http://www.alanwood.net/unicode/search.html`

**Comment by Intelligent2013** [comment]
@ronaldtse FYI.

**Comment by Intelligent2013** [comment]
One more issue:
```
SEVERE: SVG graphic could not be built. Reason: org.apache.batik.bridge.BridgeException: Content is not allowed in prolog.
org.apache.batik.bridge.BridgeException: Content is not allowed in prolog.
	at org.apache.batik.bridge.BridgeContext.getReferencedNode(Unknown Source)
	at org.apache.batik.bridge.BridgeContext.getReferencedElement(Unknown Source)
	at org.apache.batik.bridge.CSSUtilities.convertClipPath(Unknown Source)
	at org.apache.batik.bridge.AbstractGraphicsNodeBridge.buildGraphicsNode(Unknown Source)
	at org.apache.batik.bridge.GVTBuilder.buildGraphicsNode(Unknown Source)
	at org.apache.batik.bridge.GVTBuilder.buildComposite(Unknown Source)
	at org.apache.batik.bridge.GVTBuilder.buildGraphicsNode(Unknown Source)
```

**Comment by Intelligent2013** [comment]
Regarding issue "SEVERE: SVG graphic could not be built. Reason: org.apache.batik.bridge.BridgeException: Content is not allowed in prolog.":

https://issues.apache.org/jira/browse/BATIK-1227 (Status: Open)
https://issues.apache.org/jira/browse/BATIK-1090 (Status: Open)

**Comment by Intelligent2013** [comment]
New issue:
```

INFO: Rendered page #435.
апр. 29, 2020 7:52:18 ПП org.apache.fop.fonts.truetype.OpenFont checkTTC
INFO: This is a TrueType collection file with 2 fonts
апр. 29, 2020 7:52:18 ПП org.apache.fop.fonts.truetype.OpenFont checkTTC
INFO: Containing the following fonts: 
апр. 29, 2020 7:52:18 ПП org.apache.fop.fonts.truetype.OpenFont checkTTC
INFO: Cambria <-- selected
апр. 29, 2020 7:52:18 ПП org.apache.fop.fonts.truetype.OpenFont checkTTC
INFO: Cambria Math
апр. 29, 2020 7:52:18 ПП org.apache.fop.fo.FOTreeBuilder fatalError
SEVERE: org.xml.sax.SAXParseException; lineNumber: 0; columnNumber: 0; For PDF/UA-1, all fonts, even the base 14 fonts, have to be embedded! Offending font: /Symbol
(Location of error unknown)org.apache.fop.pdf.PDFConformanceException: For PDF/UA-1, all fonts, even the base 14 fonts, have to be embedded! Offending font: /Symbol
Success!
```

But PDF is empty (15 bytes only).

**Comment by Intelligent2013** [comment]
I've turned off (on my laptop) PDF/UA feature and found that image (in `<figure id="fig-surface-3d-or-volume-2d-elements-triangle-cubic">`) contains some text with font Symbol:
```
<text
           id="text32"
           style="font-variant:normal;font-weight:normal;font-size:12px;font-family:Symbol;-inkscape-font-specification:Symbol;writing-mode:lr-tb;fill:#000000;fill-opacity:1;fill-rule:nonzero;stroke:none"
           transform="matrix(1,0,0,-1,115.28,164.92)">...
```

SVG renders  in PDF as vector images with text (not bitmap), therefore Symbol font (or another fonts) should be determined in FOP config or replaced to another.

**Comment by ronaldtse** [comment]
Wow great find. We can’t do a simple strip of all fonts because symbols mean something.

We probably need a map of compatible fonts eg. Symbol to “something” we support. 

Doesn’t SVG support font embedding? If we require SVG files to self-sufficient SVG files, then we can use that font?

**Comment by ronaldtse** [comment]
@ronaldtse today I tried again with the SVG images but encountered this:
PDF:
<img width="609" alt="Screen Shot 2020-05-05 at 1 08 30 AM" src="https://user-images.githubusercontent.com/11865/80993014-f1a5ab80-8e6c-11ea-91b6-ae202925ee05.png">

Word:
<img width="494" alt="Screen Shot 2020-05-05 at 1 08 47 AM" src="https://user-images.githubusercontent.com/11865/80993045-fbc7aa00-8e6c-11ea-8969-5958d75db13c.png">

When the image is PNG, PDF works. When image is in SVG, PDF shows nothing.

**Comment by Intelligent2013** [comment]
@ronaldtse In the current version of mn2pdf a few SVG show in PDF - with font-face issue. But there are a lot of SVG, which batik can't process. Looks like these SVG contain 'url' function that batik can't process. This error you should see:
`SEVERE: SVG graphic could not be built. Reason: org.apache.batik.bridge.BridgeException: Content is not allowed in prolog.`

**Comment by Intelligent2013** [comment]
![изображение](https://user-images.githubusercontent.com/5559926/80993943-99f34a00-8e44-11ea-9d18-b154135e9187.png)

**Comment by Intelligent2013** [comment]
![изображение](https://user-images.githubusercontent.com/5559926/80993992-b099a100-8e44-11ea-8984-aa8c637a33fe.png)

**Comment by Intelligent2013** [comment]
The images above are SVG graphics. Please note that PDF with turned-off UA compliance feature, because these SVG have font-family with unknown (for mn2pdf) font.

**Comment by Intelligent2013** [comment]
Another SVG can't be displayed, because they contain 'url' function, which batik can't process properly (my preliminary opinion).

**Comment by ronaldtse** [comment]
@Intelligent2013 it seems that the issues you posted are relevant and they have patches provided. But the Batik project hasn't accepted those yet. Is it possible to patch Batik (or contribute to it) to fix it?

Otherwise, can we use another SVG library like JFree? (https://github.com/jfree/jfreesvg)

**Comment by Intelligent2013** [comment]
> @Intelligent2013 it seems that the issues you posted are relevant and they have patches provided. But the Batik project hasn't accepted those yet. Is it possible to patch Batik (or contribute to it) to fix it?

I'd like to try it in nearest days, if I'll found a time with all new issues)

> Otherwise, can we use another SVG library like JFree? (https://github.com/jfree/jfreesvg)

I'll try it also, looks like someone integrate it into Apache FOP: http://www.jfree.org/forum/viewtopic.php?t=22724

**Comment by Intelligent2013** [comment]
I've solved this issue:
```
SEVERE: SVG graphic could not be built. Reason: org.apache.batik.bridge.BridgeException: Content is not allowed in prolog.
```
Updated version: https://github.com/metanorma/mn2pdf/releases/download/v1.14/mn2pdf-1.14.jar
