### ISSUE TITLE
ISO crashes on ISO 690 document

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-native-pdf#165]
Full log of PDF errors. I think `footnote_11` represents an identical footnote that is repeated in multiple locations?

```
javax.xml.transform.TransformerException: org.apache.fop.fo.ValidationException: Property ID "footnote_11" (found on "fo:inline") previously used; ID values must be unique within a document! (See fo:inline, id=footnote_11)
	at org.apache.xalan.templates.ElemValueOf.execute(ElemValueOf.java:290)
	at org.apache.xalan.transformer.TransformerImpl.executeChildTemplates(TransformerImpl.java:2402)
	at org.apache.xalan.templates.ElemLiteralResult.execute(ElemLiteralResult.java:1376)
	at org.apache.xalan.transformer.TransformerImpl.executeChildTemplates(TransformerImpl.java:2402)
	at org.apache.xalan.templates.ElemLiteralResult.execute(ElemLiteralResult.java:1376)
	at org.apache.xalan.transformer.TransformerImpl.executeChildTemplates(TransformerImpl.java:2402)
	at org.apache.xalan.templates.ElemLiteralResult.execute(ElemLiteralResult.java:1376)
	at org.apache.xalan.transformer.TransformerImpl.executeChildTemplates(TransformerImpl.java:2402)
	at org.apache.xalan.templates.ElemLiteralResult.execute(ElemLiteralResult.java:1376)
	at org.apache.xalan.templates.ElemApplyTemplates.transformSelectedNodes(ElemApplyTemplates.java:395)
	at org.apache.xalan.templates.ElemApplyTemplates.execute(ElemApplyTemplates.java:178)
	at org.apache.xalan.transformer.TransformerImpl.executeChildTemplates(TransformerImpl.java:2402)
	at org.apache.xalan.templates.ElemElement.constructNode(ElemElement.java:341)
	at org.apache.xalan.templates.ElemElement.execute(ElemElement.java:290)
	at org.apache.xalan.templates.ElemApplyTemplates.transformSelectedNodes(ElemApplyTemplates.java:395)
	at org.apache.xalan.templates.ElemApplyTemplates.execute(ElemApplyTemplates.java:178)
	at org.apache.xalan.templates.ElemApplyTemplates.transformSelectedNodes(ElemApplyTemplates.java:395)
	at org.apache.xalan.templates.ElemApplyTemplates.execute(ElemApplyTemplates.java:178)
	at org.apache.xalan.templates.ElemApplyTemplates.transformSelectedNodes(ElemApplyTemplates.java:395)
	at org.apache.xalan.templates.ElemApplyTemplates.execute(ElemApplyTemplates.java:178)
	at org.apache.xalan.templates.ElemApplyTemplates.transformSelectedNodes(ElemApplyTemplates.java:395)
	at org.apache.xalan.templates.ElemApplyTemplates.execute(ElemApplyTemplates.java:178)
	at org.apache.xalan.transformer.TransformerImpl.executeChildTemplates(TransformerImpl.java:2402)
	at org.apache.xalan.templates.ElemLiteralResult.execute(ElemLiteralResult.java:1376)
	at org.apache.xalan.transformer.TransformerImpl.executeChildTemplates(TransformerImpl.java:2402)
	at org.apache.xalan.templates.ElemLiteralResult.execute(ElemLiteralResult.java:1376)
	at org.apache.xalan.transformer.TransformerImpl.executeChildTemplates(TransformerImpl.java:2402)
	at org.apache.xalan.templates.ElemLiteralResult.execute(ElemLiteralResult.java:1376)
	at org.apache.xalan.transformer.TransformerImpl.executeChildTemplates(TransformerImpl.java:2402)
	at org.apache.xalan.templates.ElemLiteralResult.execute(ElemLiteralResult.java:1376)
	at org.apache.xalan.transformer.TransformerImpl.executeChildTemplates(TransformerImpl.java:2402)
	at org.apache.xalan.transformer.TransformerImpl.applyTemplateToNode(TransformerImpl.java:2272)
	at org.apache.xalan.transformer.TransformerImpl.transformNode(TransformerImpl.java:1358)
	at org.apache.xalan.transformer.TransformerImpl.transform(TransformerImpl.java:711)
	at org.apache.xalan.transformer.TransformerImpl.transform(TransformerImpl.java:1275)
	at org.apache.xalan.transformer.TransformerImpl.transform(TransformerImpl.java:1253)
	at com.metanorma.fop.mn2pdf.runFOP(mn2pdf.java:200)
	at com.metanorma.fop.mn2pdf.convertmn2pdf(mn2pdf.java:155)
	at com.metanorma.fop.mn2pdf.main(mn2pdf.java:280)
Caused by: org.apache.fop.fo.ValidationException: Property ID "footnote_11" (found on "fo:inline") previously used; ID values must be unique within a document! (See fo:inline, id=footnote_11)
	at org.apache.fop.events.ValidationExceptionFactory.createException(ValidationExceptionFactory.java:38)
	at org.apache.fop.events.EventExceptionManager.throwException(EventExceptionManager.java:58)
	at org.apache.fop.events.DefaultEventBroadcaster$1.invoke(DefaultEventBroadcaster.java:173)
	at com.sun.proxy.$Proxy5.idNotUnique(Unknown Source)
	at org.apache.fop.fo.FObj.checkId(FObj.java:238)
	at org.apache.fop.fo.FObj.startOfNode(FObj.java:186)
	at org.apache.fop.fo.flow.Inline.startOfNode(Inline.java:77)
	at org.apache.fop.fo.FOTreeBuilder$MainFOHandler.startElement(FOTreeBuilder.java:339)
	at org.apache.fop.fo.FOTreeBuilder.startElement(FOTreeBuilder.java:179)
	at org.apache.xml.serializer.ToXMLSAXHandler.closeStartTag(ToXMLSAXHandler.java:206)
	at org.apache.xml.serializer.ToXMLSAXHandler.characters(ToXMLSAXHandler.java:524)
	at org.apache.xpath.objects.XString.dispatchCharactersEvents(XString.java:206)
	at org.apache.xpath.objects.XObject.dispatchCharactersEvents(XObject.java:151)
	at org.apache.xpath.Expression.executeCharsToContentHandler(Expression.java:315)
	at org.apache.xalan.templates.ElemValueOf.execute(ElemValueOf.java:274)
	... 38 more
---------
org.apache.fop.fo.ValidationException: Property ID "footnote_11" (found on "fo:inline") previously used; ID values must be unique within a document! (See fo:inline, id=footnote_11)
	at org.apache.fop.events.ValidationExceptionFactory.createException(ValidationExceptionFactory.java:38)
	at org.apache.fop.events.EventExceptionManager.throwException(EventExceptionManager.java:58)
	at org.apache.fop.events.DefaultEventBroadcaster$1.invoke(DefaultEventBroadcaster.java:173)
	at com.sun.proxy.$Proxy5.idNotUnique(Unknown Source)
	at org.apache.fop.fo.FObj.checkId(FObj.java:238)
	at org.apache.fop.fo.FObj.startOfNode(FObj.java:186)
	at org.apache.fop.fo.flow.Inline.startOfNode(Inline.java:77)
	at org.apache.fop.fo.FOTreeBuilder$MainFOHandler.startElement(FOTreeBuilder.java:339)
	at org.apache.fop.fo.FOTreeBuilder.startElement(FOTreeBuilder.java:179)
	at org.apache.xml.serializer.ToXMLSAXHandler.closeStartTag(ToXMLSAXHandler.java:206)
	at org.apache.xml.serializer.ToXMLSAXHandler.characters(ToXMLSAXHandler.java:524)
	at org.apache.xpath.objects.XString.dispatchCharactersEvents(XString.java:206)
	at org.apache.xpath.objects.XObject.dispatchCharactersEvents(XObject.java:151)
	at org.apache.xpath.Expression.executeCharsToContentHandler(Expression.java:315)
	at org.apache.xalan.templates.ElemValueOf.execute(ElemValueOf.java:274)
	at org.apache.xalan.transformer.TransformerImpl.executeChildTemplates(TransformerImpl.java:2402)
	at org.apache.xalan.templates.ElemLiteralResult.execute(ElemLiteralResult.java:1376)
	at org.apache.xalan.transformer.TransformerImpl.executeChildTemplates(TransformerImpl.java:2402)
	at org.apache.xalan.templates.ElemLiteralResult.execute(ElemLiteralResult.java:1376)
	at org.apache.xalan.transformer.TransformerImpl.executeChildTemplates(TransformerImpl.java:2402)
	at org.apache.xalan.templates.ElemLiteralResult.execute(ElemLiteralResult.java:1376)
	at org.apache.xalan.transformer.TransformerImpl.executeChildTemplates(TransformerImpl.java:2402)
	at org.apache.xalan.templates.ElemLiteralResult.execute(ElemLiteralResult.java:1376)
	at org.apache.xalan.templates.ElemApplyTemplates.transformSelectedNodes(ElemApplyTemplates.java:395)
	at org.apache.xalan.templates.ElemApplyTemplates.execute(ElemApplyTemplates.java:178)
	at org.apache.xalan.transformer.TransformerImpl.executeChildTemplates(TransformerImpl.java:2402)
	at org.apache.xalan.templates.ElemElement.constructNode(ElemElement.java:341)
	at org.apache.xalan.templates.ElemElement.execute(ElemElement.java:290)
	at org.apache.xalan.templates.ElemApplyTemplates.transformSelectedNodes(ElemApplyTemplates.java:395)
	at org.apache.xalan.templates.ElemApplyTemplates.execute(ElemApplyTemplates.java:178)
	at org.apache.xalan.templates.ElemApplyTemplates.transformSelectedNodes(ElemApplyTemplates.java:395)
	at org.apache.xalan.templates.ElemApplyTemplates.execute(ElemApplyTemplates.java:178)
	at org.apache.xalan.templates.ElemApplyTemplates.transformSelectedNodes(ElemApplyTemplates.java:395)
	at org.apache.xalan.templates.ElemApplyTemplates.execute(ElemApplyTemplates.java:178)
	at org.apache.xalan.templates.ElemApplyTemplates.transformSelectedNodes(ElemApplyTemplates.java:395)
	at org.apache.xalan.templates.ElemApplyTemplates.execute(ElemApplyTemplates.java:178)
	at org.apache.xalan.transformer.TransformerImpl.executeChildTemplates(TransformerImpl.java:2402)
	at org.apache.xalan.templates.ElemLiteralResult.execute(ElemLiteralResult.java:1376)
	at org.apache.xalan.transformer.TransformerImpl.executeChildTemplates(TransformerImpl.java:2402)
	at org.apache.xalan.templates.ElemLiteralResult.execute(ElemLiteralResult.java:1376)
	at org.apache.xalan.transformer.TransformerImpl.executeChildTemplates(TransformerImpl.java:2402)
	at org.apache.xalan.templates.ElemLiteralResult.execute(ElemLiteralResult.java:1376)
	at org.apache.xalan.transformer.TransformerImpl.executeChildTemplates(TransformerImpl.java:2402)
	at org.apache.xalan.templates.ElemLiteralResult.execute(ElemLiteralResult.java:1376)
	at org.apache.xalan.transformer.TransformerImpl.executeChildTemplates(TransformerImpl.java:2402)
	at org.apache.xalan.transformer.TransformerImpl.applyTemplateToNode(TransformerImpl.java:2272)
	at org.apache.xalan.transformer.TransformerImpl.transformNode(TransformerImpl.java:1358)
	at org.apache.xalan.transformer.TransformerImpl.transform(TransformerImpl.java:711)
	at org.apache.xalan.transformer.TransformerImpl.transform(TransformerImpl.java:1275)
	at org.apache.xalan.transformer.TransformerImpl.transform(TransformerImpl.java:1253)
	at com.metanorma.fop.mn2pdf.runFOP(mn2pdf.java:200)
	at com.metanorma.fop.mn2pdf.convertmn2pdf(mn2pdf.java:155)
	at com.metanorma.fop.mn2pdf.main(mn2pdf.java:280)
```

Tracked here: https://github.com/metanorma/iso-690/issues/5

**Comment by ronaldtse** [comment]
(already passed sample to @Intelligent2013 )

The issue is with identical footnotes -- where the same footnote applies to multiple locations.

**Comment by Intelligent2013** [comment]
Issue fixed.
