### ISSUE TITLE
When link is an empty `mailto:` mn2pdf crashes

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-native-pdf#186]
When link is an empty `mailto:` mn2pdf crashes.

```xml
<p id="_697431ce-3d0d-442d-82ec-ae00517533ed">
  If there is difficulty accessing these sites contact ISO Central Secretariat
  or contact the ISO TC 184/SC4 Secretariat directly at: 
  <link target="mailto:">
  sc4sec@cme.nist.gov
</link>
.
```

Error:
```
SEVERE: Error while rendering page 30. Reason: java.lang.IllegalStateException: java.net.URISyntaxException: Expected scheme-specific part at index 7: mailto:
java.lang.IllegalStateException: java.net.URISyntaxException: Expected scheme-specific part at index 7: mailto:
	at org.apache.fop.pdf.PDFFactory.getFileUri(PDFFactory.java:668)
	at org.apache.fop.pdf.PDFFactory.getTargetUri(PDFFactory.java:626)
	at org.apache.fop.pdf.PDFFactory.getExternalAction(PDFFactory.java:565)
```

**Comment by ronaldtse** [comment]
The XML looks like this:
```xml
<p id="_820a6d42-fc98-4778-88f3-0d835a622a29">
  If there is difficulty accessing these sites contact ISO Central Secretariat
  or contact the ISO TC 184/SC4 Secretariat directly at: 
  <link target="mailto:sc4sec@cme.nist.gov"/>
  .</p>
```

**Comment by ronaldtse** [comment]
It gets rendered like this:
<img width="574" alt="Screen Shot 2020-05-12 at 11 58 41 AM" src="https://user-images.githubusercontent.com/11865/81637046-eee81f00-9447-11ea-8138-6df3a29bde9d.png">

**Comment by Intelligent2013** [comment]
Fixed.
