### ISSUE TITLE
OGC: 00-027 PDF error

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/mn-native-pdf#250]
Error (https://github.com/metanorma/mn-native-pdf/runs/1117763978)
```
Input: Fonts path (~/.metanorma/fonts)
Input: XML (sources/ogc-00-027.presentation.xml)
Input: XSL (/Users/runner/work/mn-native-pdf/mn-native-pdf/xslt/ogc.test-suite.xsl)
Output: PDF (documents/ogc-00-027.presentation.pdf)

Transforming...
Unable to create basic Accelerated OpenGL renderer.
Unable to create basic Accelerated OpenGL renderer.
Core Image is now using the software OpenGL renderer. This will be slow.
Sep 15, 2020 1:23:55 PM org.apache.fop.apps.FopConfParser configure
INFO: Default page-height set to: 11.00in
Sep 15, 2020 1:23:55 PM org.apache.fop.apps.FopConfParser configure
INFO: Default page-width set to: 8.50in
Sep 15, 2020 1:23:56 PM org.apache.fop.events.LoggingEventListener processEvent
INFO: Rendered page #1.
javax.xml.transform.TransformerException: org.apache.fop.fo.ValidationException: "fo:list-item-body" is missing child elements. Required content model: marker* (%block;)+ (See position 103:298)
	at org.apache.xalan.transformer.TransformerIdentityImpl.transform(TransformerIdentityImpl.java:502)
	at com.metanorma.fop.mn2pdf.runFOP(mn2pdf.java:292)
	at com.metanorma.fop.mn2pdf.convertmn2pdf(mn2pdf.java:225)
	at com.metanorma.fop.mn2pdf.main(mn2pdf.java:470)
```

**Comment by Intelligent2013** [comment]
This error occurs for MacOS.
For Ubuntu it's ok:
```
2020-09-15T13:20:11.4053644Z cp mn-samples-ogc/documents/00-027.presentation.xml sources/ogc-00-027.presentation.xml
2020-09-15T13:20:11.4081903Z FILENAME=sources/ogc-00-027.presentation.xml; \
2020-09-15T13:20:11.4082894Z MN_FLAVOR=$(xmllint --xpath 'name(*)' ${FILENAME} | cut -d '-' -f 1); \
2020-09-15T13:20:11.4083742Z DOCTYPE=$(xmllint --xpath "(//*[local-name()='doctype'])[1]/text()" ${FILENAME}); \
2020-09-15T13:20:11.4084893Z XSLT_PATH=/home/runner/work/mn-native-pdf/mn-native-pdf/xslt/${MN_FLAVOR}.${DOCTYPE}.presentation.xsl; \
2020-09-15T13:20:11.4086178Z java -Xss5m -Xmx1024m -jar mn2pdf-1.20.jar --xml-file $FILENAME --xsl-file $XSLT_PATH --pdf-file documents/ogc-00-027.presentation.pdf	
2020-09-15T13:20:11.5030676Z mn2pdf 
2020-09-15T13:20:11.5031271Z 
2020-09-15T13:20:11.5031604Z 
2020-09-15T13:20:11.5032149Z Preparing...
2020-09-15T13:20:11.5127760Z Input: Fonts path (~/.metanorma/fonts)
2020-09-15T13:20:11.5131039Z Input: XML (sources/ogc-00-027.presentation.xml)
2020-09-15T13:20:11.5132648Z Input: XSL (/home/runner/work/mn-native-pdf/mn-native-pdf/xslt/ogc.test-suite.presentation.xsl)
2020-09-15T13:20:11.5134073Z Output: PDF (documents/ogc-00-027.presentation.pdf)
...
2020-09-15T13:20:16.3546933Z Success!
```

The differences is:
- MacOS:
```
Input: XSL (/Users/runner/work/mn-native-pdf/mn-native-pdf/xslt/ogc.test-suite.xsl)
```
(without `presentation' suffix)

- Ubuntu:
```
 Input: XSL (/home/runner/work/mn-native-pdf/mn-native-pdf/xslt/ogc.test-suite.presentation.xsl)
```
(with `presentation' suffix)

**Comment by Intelligent2013** [comment]
Problem solved:
```
2020-09-15T16:21:03.3322850Z Preparing...
2020-09-15T16:21:03.3354860Z Input: Fonts path (~/.metanorma/fonts)
2020-09-15T16:21:03.3356610Z Input: XML (sources/ogc-00-027.presentation.xml)
2020-09-15T16:21:03.3358280Z Input: XSL (/Users/runner/work/mn-native-pdf/mn-native-pdf/xslt/ogc.test-suite.presentation.xsl)
2020-09-15T16:21:03.3359520Z Output: PDF (documents/ogc-00-027.presentation.pdf)
...
2020-09-15T16:21:08.9714330Z Success!
```
The solition: in Makefile more specific rules should be upper, i.e. `documents/%.presentation.pdf:...` should be before than `documents/%.pdf:...`
