### ISSUE TITLE
Error: NoMethodError: undefined method `text' for nil:NilClass

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/mn-native-pdf#253]
This error relates to `relaton-iho-1.3.2` and iho documents:
```
2020-09-15T16:39:14.7023450Z Use `bundle info [gemname]` to see where a bundled gem is installed.
2020-09-15T16:39:14.7074460Z bundle exec relaton concatenate \
2020-09-15T16:39:14.7075450Z 	  -t "mn2pdf samples" \
2020-09-15T16:39:14.7076040Z 		-g "Metanorma" \
2020-09-15T16:39:14.7076360Z 		documents documents.rxl
2020-09-15T16:39:17.1979740Z bundler: failed to load command: relaton (/Users/runner/hostedtoolcache/Ruby/2.6.6/x64/bin/relaton)
2020-09-15T16:39:17.1989720Z NoMethodError: undefined method `text' for nil:NilClass
2020-09-15T16:39:17.1990910Z   /Users/runner/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/relaton-iho-1.3.2/lib/relaton_iho/xml_parser.rb:46:in `iho_group'
2020-09-15T16:39:17.1992310Z   /Users/runner/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/relaton-iho-1.3.2/lib/relaton_iho/xml_parser.rb:31:in `block (2 levels) in fetch_editorialgroup'
2020-09-15T16:39:17.1993680Z   /Users/runner/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/node_set.rb:238:in `block in each'
```

Possible solution: try to update mn-samples-ihorepo,  gh-pages branch.

**Comment by Intelligent2013** [comment]
There isn't issue.
