### ISSUE TITLE
PNG image processing error

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/mn-native-pdf#336]
Source: https://github.com/metanorma/metanorma-ogc/issues/323

This error occurs for one image from the source document (35 images render ok):

```
Image not available. URI: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAACMoAAAOaCAYAAABjwCyHAAAABGdBTUEAALGPC/xh...
Reason: org.apache.xmlgraphics.image.loader.ImageException: I/O error while extracting image metadata: Error reading PNG metadata (See position 1446:181859)
org.apache.xmlgraphics.image.loader.ImageException: I/O error while extracting image metadata: Error reading PNG metadata
        at org.apache.xmlgraphics.image.loader.impl.imageio.PreloaderImageIO.preloadImage(PreloaderImageIO.java:91)
        at org.apache.xmlgraphics.image.loader.ImageManager.preloadImage(ImageManager.java:176)
        at org.apache.xmlgraphics.image.loader.cache.ImageCache.needImageInfo(ImageCache.java:128)
        at org.apache.xmlgraphics.image.loader.ImageManager.getImageInfo(ImageManager.java:123)
        at org.apache.fop.fo.flow.ExternalGraphic.bind(ExternalGraphic.java:81)
        at org.apache.fop.fo.FObj.processNode(FObj.java:131)
        at org.apache.fop.fo.FOTreeBuilder$MainFOHandler.startElement(FOTreeBuilder.java:293)
        at org.apache.fop.fo.FOTreeBuilder.startElement(FOTreeBuilder.java:179)
        at org.apache.xalan.transformer.TransformerIdentityImpl.startElement(TransformerIdentityImpl.java:1073)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source)
        at org.apache.xalan.transformer.TransformerIdentityImpl.transform(TransformerIdentityImpl.java:485)
        at org.metanorma.fop.PDFGenerator.runFOP(PDFGenerator.java:518)
        at org.metanorma.fop.PDFGenerator.convertmn2pdf(PDFGenerator.java:403)
        at org.metanorma.fop.PDFGenerator.process(PDFGenerator.java:272)
        at org.metanorma.fop.mn2pdf.main(mn2pdf.java:334)
Caused by: javax.imageio.IIOException: Error reading PNG metadata
        at com.sun.imageio.plugins.png.PNGImageReader.readMetadata(Unknown Source)
        at com.sun.imageio.plugins.png.PNGImageReader.getImageMetadata(Unknown Source)
        at org.apache.xmlgraphics.image.loader.impl.imageio.PreloaderImageIO.preloadImage(PreloaderImageIO.java:71)
        ... 24 more
Caused by: javax.imageio.IIOException: Failed to read a chunk of type 1649100612
        ... 27 more

```

Meta information:
![image](https://user-images.githubusercontent.com/5559926/144293020-16748bd2-e91e-45f5-bbab-40f0cd51e563.png)

**Comment by Intelligent2013** [comment]
No error after re-saving (in XnView).

**Comment by ronaldtse** [comment]
The PNG content is converted into data URI by metanorma. 

We need to know whether this problem originated from our inlining process or the original image file. 

If the latter, we need to tell the user to fix the image somehow.

**Comment by Intelligent2013** [comment]
The issue in JVM class `com.sun.imageio.plugins.png.PNGImageReader`. It can't read the metadata from some PNG files.
I've tried to read the problematic PNG from OGC document on different JVM - Oracle and non-Oracle (used util for testing purposes - https://github.com/Intelligent2013/imageMetaInfo/) and all of them throw error:

Windows:
```
JDK/JRE vendor: Oracle Corporation
Java version: 1.8.0_311
Java runtime version: 1.8.0_311-b11
JVM implementation: Java HotSpot(TM) 64-Bit Server VM
JVM implementation vendor: Oracle Corporation
com.sun.imageio.plugins.png.PNGImageReader
Exception in thread "main" javax.imageio.IIOException: Error reading PNG metadata
        at com.sun.imageio.plugins.png.PNGImageReader.readMetadata(PNGImageReader.java:796)
        at com.sun.imageio.plugins.png.PNGImageReader.readImage(PNGImageReader.java:1256)
        at com.sun.imageio.plugins.png.PNGImageReader.read(PNGImageReader.java:1614)
        at com.mycompany.ImageMetaInfo.main(ImageMetaInfo.java:30)
Caused by: javax.imageio.IIOException: Failed to read a chunk of type 1649100612
        at com.sun.imageio.plugins.png.PNGImageReader.readMetadata(PNGImageReader.java:790)
        ... 3 more


```
Windows/MacOS:
```
JDK/JRE vendor: AdoptOpenJDK
Java version: 11.0.11
Java runtime version: 11.0.11+9
JVM implementation: OpenJDK 64-Bit Server VM
JVM implementation vendor: AdoptOpenJDK
com.sun.imageio.plugins.png.PNGImageReader
Exception in thread "main" javax.imageio.IIOException: Error reading PNG metadata
        at java.desktop/com.sun.imageio.plugins.png.PNGImageReader.readMetadata(PNGImageReader.java:891)
        at java.desktop/com.sun.imageio.plugins.png.PNGImageReader.readImage(PNGImageReader.java:1395)
        at java.desktop/com.sun.imageio.plugins.png.PNGImageReader.read(PNGImageReader.java:1810)
        at com.mycompany.ImageMetaInfo.main(ImageMetaInfo.java:30)
Caused by: javax.imageio.IIOException: Failed to read a chunk of type 1649100612
        at java.desktop/com.sun.imageio.plugins.png.PNGImageReader.readMetadata(PNGImageReader.java:886)
        ... 3 more
```

Ubuntu:
```
JDK/JRE vendor: Private Build
Java version: 1.8.0_292
Java runtime version: 1.8.0_292-8u292-b10-0ubuntu1~20.04-b10
JVM implementation: OpenJDK 64-Bit Server VM
JVM implementation vendor: Private Build
com.sun.imageio.plugins.png.PNGImageReader
Exception in thread "main" javax.imageio.IIOException: Error reading PNG metadata
at com.sun.imageio.plugins.png.PNGImageReader.readMetadata(PNGImageReader.java:796)
at com.sun.imageio.plugins.png.PNGImageReader.readImage(PNGImageReader.java:1256)
at com.sun.imageio.plugins.png.PNGImageReader.read(PNGImageReader.java:1614)
at com.mycompany.ImageMetaInfo.main(ImageMetaInfo.java:30)
Caused by: javax.imageio.IIOException: Failed to read a chunk of type 1649100612
at com.sun.imageio.plugins.png.PNGImageReader.readMetadata(PNGImageReader.java:790)
... 3 more
```

I assume the issue in `tEXtdate` section before `IDAT` sections:
![image](https://user-images.githubusercontent.com/5559926/144403353-73d12f18-0798-4e95-82a9-b2abaf94b9f4.png)
It seems Java library can't read it...

As workaround solution I propose to re-save such problematic PNGs with some image viewer - XnView, IrfanView, etc. (except MS Paint that doesn't change image at re-saving).

**Comment by ronaldtse** [comment]
@Intelligent2013 this issue seems relevant to the following OpenJDK issues:

* https://bugs.openjdk.java.net/browse/JDK-8211422
* https://bugs.openjdk.java.net/browse/JDK-8191431

Could you help report this bug to the OpenJDK team?

Are you proposing that we can auto-convert these problematic PNGs with XnView in Java on this exception? Or is this advice for the authors?

**Comment by Intelligent2013** [comment]
> Could you help report this bug to the OpenJDK team?

@ronaldtse yes. Can we share the example image (Figure 13) from OGC document on openjdk tracker?


> Are you proposing that we can auto-convert these problematic PNGs with XnView in Java on this exception? Or is this advice for the authors?

For the authors.

**Comment by Intelligent2013** [comment]
@ronaldtse as you noticed in https://github.com/metanorma/metanorma-ogc/issues/323#issuecomment-986413687, it is a broken PNG file. I think that we shouldn't report this bug to the OpenJDK issues tracker.
Closing. Please open, if this issue is still actual.
