### ISSUE TITLE
Rendering formattedref instead of bibitem content

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/mn-native-pdf#356]
From: https://github.com/metanorma/metanorma-standoc/issues/479#issuecomment-1106399600

> formattedref replaces the content of bibitem in Presentation XML, with three exceptions retained, which I believe to be necessary to process separately.
> 
> * docidentifier, to generate reference tags
> * uri, in order to enable hyperlinking to be inserted into cross-references
> * note, in order to enable footnotes to be inserted after the reference tag (which we process separately to the reference citation proper)

For all xslt.

**Comment by Intelligent2013** [comment]
I've tried to generate example xml for mn-samples-iso:
- updated Gemfile:
```
source "https://rubygems.org"

gem "metanorma-cli"
gem "metanorma-iso", git: "https://github.com/metanorma/metanorma-iso", branch: "features/relaton-render"
gem "metanorma", git: "https://github.com/metanorma/metanorma", branch: "main"
gem "metanorma-standoc", git: "https://github.com/metanorma/metanorma-standoc", branch: "main"
gem "isodoc", git: "https://github.com/metanorma/isodoc", branch: "features/relaton-render"
gem "sassc"
```

- bundle update
- cd sources\international-standard
- bundle exec metanorma -t iso -x presentation rice-en.final.adoc 
```
Fatal Error: wrong number of arguments (given 3, expected 2)
Traceback (most recent call last):
        33: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/bin/metanorma:23:in `<main>'
        32: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/bin/metanorma:23:in `load'
        31: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/metanorma-cli-1.5.14/exe/metanorma:43:in `<top (required)>'
        30: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/metanorma-cli-1.5.14/exe/metanorma:25:in `block in <top (required)>'
        29: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/metanorma-cli-1.5.14/lib/metanorma/cli.rb:34:in `start'
        28: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
        27: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
        26: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
        25: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-hollaback-0.2.1/lib/thor/hollaback.rb:68:in `run'
        24: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
        23: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/metanorma-cli-1.5.14/lib/metanorma/cli/command.rb:47:in `compile'
        22: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/metanorma-cli-1.5.14/lib/metanorma/cli/command.rb:47:in `each'
        21: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/metanorma-cli-1.5.14/lib/metanorma/cli/command.rb:47:in `block in compile'
        20: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/metanorma-cli-1.5.14/lib/metanorma/cli/command.rb:241:in `compile_document'
        19: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/metanorma-cli-1.5.14/lib/metanorma/cli/compiler.rb:35:in `compile'
        18: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/metanorma-cli-1.5.14/lib/metanorma/cli/compiler.rb:30:in `compile'
        17: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/metanorma-cli-1.5.14/lib/metanorma/cli/compiler.rb:45:in `compile_file'
        16: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/bundler/gems/metanorma-bebce34126cc/lib/metanorma/compile.rb:33:in `compile'
        15: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/bundler/gems/metanorma-bebce34126cc/lib/metanorma/compile.rb:42:in `process_input'
        14: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/bundler/gems/metanorma-bebce34126cc/lib/metanorma/compile.rb:59:in `process_input_adoc'
        13: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/bundler/gems/metanorma-bebce34126cc/lib/metanorma/processor.rb:21:in `input_to_isodoc'
        12: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/bundler/gems/metanorma-bebce34126cc/lib/metanorma/input/asciidoc.rb:18:in `process'
        11: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/asciidoctor-2.0.17/lib/asciidoctor/convert.rb:120:in `convert'
        10: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/asciidoctor-2.0.17/lib/asciidoctor/document.rb:955:in `convert'
         9: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/bundler/gems/metanorma-standoc-6046c490f6fd/lib/metanorma/standoc/utils.rb:13:in `convert'
         8: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/bundler/gems/metanorma-standoc-6046c490f6fd/lib/metanorma/standoc/base.rb:103:in `document'
         7: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/bundler/gems/metanorma-standoc-6046c490f6fd/lib/metanorma/standoc/base.rb:113:in `document1'
         6: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/bundler/gems/metanorma-iso-3a092e730a9c/lib/metanorma/iso/base.rb:45:in `init'
         5: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/bundler/gems/metanorma-standoc-6046c490f6fd/lib/metanorma/standoc/base.rb:34:in `init'
         4: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/bundler/gems/metanorma-standoc-6046c490f6fd/lib/metanorma/standoc/base.rb:90:in `init_i18n'
         3: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/bundler/gems/metanorma-standoc-6046c490f6fd/lib/metanorma/standoc/utils.rb:64:in `isodoc'
         2: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/bundler/gems/metanorma-iso-3a092e730a9c/lib/isodoc/iso/init.rb:19:in `i18n_init'
         1: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/bundler/gems/metanorma-iso-3a092e730a9c/lib/isodoc/iso/init.rb:19:in `new'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/isodoc-i18n-1.0.5/lib/isodoc/i18n.rb:57:in `initialize': wrong number of arguments (given 3, expected 2) (ArgumentError)
```
Will wait next gem releases.

**Comment by Intelligent2013** [comment]
To do: update xslt
- [ ] BIPM
- [ ] BSI
- [ ] CSD
- [ ] CSA
- [ ] IEC
- [ ] IHO
- [ ] ISO
- [ ] ITU
- [ ] JCGM
- [ ] M3AAWG
- [ ] MPFD
- [ ] NIST CSWP
- [ ] NIST SP
- [ ] OGC
- [ ] OGC White Paper
- [ ] Ribose
- [ ] UN plenary
- [ ] UN recommendation

**Comment by Intelligent2013** [comment]
Done.
