### ISSUE TITLE
ITU: Error in table cell?

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-native-pdf#39]
See `itu-Y.3507-201812.xml`

```
2019-12-04T19:40:45.6310680Z Dec 04, 2019 7:40:45 PM org.apache.fop.events.LoggingEventListener processEvent
2019-12-04T19:40:45.6312510Z INFO: An fo:block  (See position 861:12) is wider than the available room in inline-progression-dimension. Adjusting end-indent based on overconstrained geometry rules (XSL 1.1, ch. 5.3.4)
2019-12-04T19:40:45.7909660Z javax.xml.transform.TransformerException: org.apache.fop.fo.ValidationException: null:2581:18: A table-cell is spanning more rows than available in its parent element.
2019-12-04T19:40:45.7914370Z 	at org.apache.xalan.transformer.TransformerIdentityImpl.transform(TransformerIdentityImpl.java:502)
2019-12-04T19:40:45.7915050Z 	at com.metanorma.fop.XML2PDF.convertXML2PDF(XML2PDF.java:93)
2019-12-04T19:40:45.7915620Z 	at com.metanorma.fop.XML2PDF.main(XML2PDF.java:148)
2019-12-04T19:40:45.7916150Z 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2019-12-04T19:40:45.7916760Z 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2019-12-04T19:40:45.7917360Z 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2019-12-04T19:40:45.7917920Z 	at java.lang.reflect.Method.invoke(Method.java:498)
2019-12-04T19:40:45.7918560Z 	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:282)
2019-12-04T19:40:45.7919130Z 	at java.lang.Thread.run(Thread.java:748)
2019-12-04T19:40:45.7920350Z Caused by: org.apache.fop.fo.ValidationException: null:2581:18: A table-cell is spanning more rows than available in its parent element.
2019-12-04T19:40:45.7921060Z 	at org.apache.fop.fo.flow.table.FixedColRowGroupBuilder.endTablePart(FixedColRowGroupBuilder.java:181)
2019-12-04T19:40:45.7921670Z 	at org.apache.fop.fo.flow.table.TablePart.finishLastRowGroup(TablePart.java:139)
2019-12-04T19:40:45.7922240Z 	at org.apache.fop.fo.flow.table.TablePart.finalizeNode(TablePart.java:116)
2019-12-04T19:40:45.7923630Z 	at org.apache.fop.fo.FONode.endOfNode(FONode.java:350)
2019-12-04T19:40:45.7924410Z 	at org.apache.fop.fo.FObj.endOfNode(FObj.java:220)
2019-12-04T19:40:45.7924800Z 	at org.apache.fop.fo.flow.table.TableBody.endOfNode(TableBody.java:48)
2019-12-04T19:40:45.7925140Z 	at org.apache.fop.fo.FOTreeBuilder$MainFOHandler.endElement(FOTreeBuilder.java:362)
2019-12-04T19:40:45.7925460Z 	at org.apache.fop.fo.FOTreeBuilder.endElement(FOTreeBuilder.java:190)
2019-12-04T19:40:45.7925810Z 	at org.apache.xalan.transformer.TransformerIdentityImpl.endElement(TransformerIdentityImpl.java:1102)
2019-12-04T19:40:45.7926180Z 	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:609)
2019-12-04T19:40:45.7926560Z 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1782)
2019-12-04T19:40:45.7926950Z 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2967)
2019-12-04T19:40:45.7927360Z 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
2019-12-04T19:40:45.7927730Z 	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
2019-12-04T19:40:45.7928110Z 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
2019-12-04T19:40:45.7928480Z 	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:842)
2019-12-04T19:40:45.7928830Z 	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771)
2019-12-04T19:40:45.7929180Z 	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
2019-12-04T19:40:45.7929520Z 	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
2019-12-04T19:40:45.7929880Z 	at org.apache.xalan.transformer.TransformerIdentityImpl.transform(TransformerIdentityImpl.java:485)
2019-12-04T19:40:45.7930190Z 	... 8 more
2019-12-04T19:40:45.7930910Z ---------
2019-12-04T19:40:45.7931640Z org.apache.fop.fo.ValidationException: null:2581:18: A table-cell is spanning more rows than available in its parent element.
2019-12-04T19:40:45.7932040Z 	at org.apache.fop.fo.flow.table.FixedColRowGroupBuilder.endTablePart(FixedColRowGroupBuilder.java:181)
2019-12-04T19:40:45.7932380Z 	at org.apache.fop.fo.flow.table.TablePart.finishLastRowGroup(TablePart.java:139)
2019-12-04T19:40:45.7932700Z 	at org.apache.fop.fo.flow.table.TablePart.finalizeNode(TablePart.java:116)
2019-12-04T19:40:45.7933010Z 	at org.apache.fop.fo.FONode.endOfNode(FONode.java:350)
2019-12-04T19:40:45.7933280Z 	at org.apache.fop.fo.FObj.endOfNode(FObj.java:220)
2019-12-04T19:40:45.7933570Z 	at org.apache.fop.fo.flow.table.TableBody.endOfNode(TableBody.java:48)
2019-12-04T19:40:45.7933890Z 	at org.apache.fop.fo.FOTreeBuilder$MainFOHandler.endElement(FOTreeBuilder.java:362)
2019-12-04T19:40:45.7934230Z 	at org.apache.fop.fo.FOTreeBuilder.endElement(FOTreeBuilder.java:190)
2019-12-04T19:40:45.7934580Z 	at org.apache.xalan.transformer.TransformerIdentityImpl.endElement(TransformerIdentityImpl.java:1102)
2019-12-04T19:40:45.7934940Z 	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:609)
2019-12-04T19:40:45.7935320Z 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1782)
2019-12-04T19:40:45.7935720Z 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2967)
2019-12-04T19:40:45.7936110Z 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
2019-12-04T19:40:45.7936480Z 	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
2019-12-04T19:40:45.7937290Z 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
2019-12-04T19:40:45.7937710Z 	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:842)
2019-12-04T19:40:45.7938050Z 	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771)
2019-12-04T19:40:45.7938390Z 	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
2019-12-04T19:40:45.7938740Z 	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
2019-12-04T19:40:45.7939090Z 	at org.apache.xalan.transformer.TransformerIdentityImpl.transform(TransformerIdentityImpl.java:485)
2019-12-04T19:40:45.7939410Z 	at com.metanorma.fop.XML2PDF.convertXML2PDF(XML2PDF.java:93)
2019-12-04T19:40:45.7939700Z 	at com.metanorma.fop.XML2PDF.main(XML2PDF.java:148)
2019-12-04T19:40:45.7939980Z 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2019-12-04T19:40:45.7940300Z 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2019-12-04T19:40:45.7940640Z 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2019-12-04T19:40:45.7940940Z 	at java.lang.reflect.Method.invoke(Method.java:498)
2019-12-04T19:40:45.7941220Z 	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:282)
2019-12-04T19:40:45.7941510Z 	at java.lang.Thread.run(Thread.java:748)
2019-12-04T19:40:46.2986640Z make: *** [documents/itu-Y.3507-201812.pdf] Error 255

```

**Comment by Intelligent2013** [comment]
@ronaldtse 
The issue in source xml, in table-i-1:
```
<table id="table-i-1">
  <name>OCP related specifications</name>
  <tbody>
    <tr>
      <td align="left">
        <strong>Family</strong>
      </td>
    </tr>
    <tr>
      <td align="left">
        <strong>Specification</strong>
      </td>
    </tr>
    <tr>
      <td align="left">
        <strong>Summary</strong>
      </td>
    </tr>
    <tr>
      <td align="left">
        <strong>Published</strong>
      </td>
    </tr>
    <tr>
      <td rowspan="8" align="left">OpenRack V2</td>
    </tr>
  </tbody>
</table>
```
The cell in **last** row has a value **rowspan**="8", but no continue.
In my local version:
```
<table id="table-i-1">
  <name>OCP related specifications</name>
  <tbody>
    <tr>
      <td align="center">
        <strong>Family</strong>
      </td>
      <td align="center">
        <strong>Specification</strong>
      </td>
      <td align="center">
        <strong>Summary</strong>
      </td>
      <td align="center">
        <strong>Published</strong>
      </td>
    </tr>
    <tr>
      <td rowspan="8" align="left">OpenRack V2</td>
      <td align="left">Twin Lakes 1S Server Design Specification V1.00 <eref type="inline" bibitemid="b-OCP_1S" citeas="b-OCP 1S"/></td>
      <td align="left">This specification describes the design of the Twin Lakes 1S server based on the Intel Xeon Processor D-2191 System-on-a-Chip (SoC).</td>
      <td align="center">2018</td>
    </tr>
    <tr>
      <td align="left">Facebook 2S Server Tioga Pass Specification V1.0 <eref type="inline" bibitemid="b-OCP_2S" citeas="b-OCP 2S"/></td>
      <td align="left">This specification describes Facebook dual sockets server Intel Motherboard v4.0<br/>
(Project name: Tioga Pass) design and design requirement to integrate Tioga Pass into Open Rack V2.</td>
      <td align="center">2018</td>
    </tr>
    <tr>
      <td align="left">Big Basin-JBOG Specification V1.0 <eref type="inline" bibitemid="b-OCP_JBOG" citeas="b-OCP JBOG"/></td>
      <td align="left">This document describes technical specifications for Facebook's Big Basin-JBOG for use in Open Rack V2.</td>
      <td align="center">2018</td>
    </tr>
    <tr>...
```

**Comment by ronaldtse** [comment]
Thanks @Intelligent2013 for the investigation! This sounds like a bug in the `isodoc` gem. Raising it there.
