### ISSUE TITLE
BIPM PDF: brochure-its90 java.lang.NullPointerException

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/mn-native-pdf#473]
No PDF for [brochure-its90-en.presentation.xml](https://github.com/metanorma/mn-samples-bipm/blob/gh-pages/documents/brochure-its90/brochure-its90-en.presentation.xml) and [brochure-its90-fr.presentation.xml](https://github.com/metanorma/mn-samples-bipm/blob/gh-pages/documents/brochure-its90/brochure-its90-fr.presentation.xml)
due the error
```
Error while rendering page 11. Reason: java.lang.NullPointerException
java.lang.NullPointerException
	at org.apache.fop.render.intermediate.IFSerializer.renderLink(IFSerializer.java:918)
	at org.apache.fop.render.intermediate.IFRenderer.renderPage(IFRenderer.java:597)
	at org.apache.fop.area.RenderPagesModel.renderPage(RenderPagesModel.java:193)
	at org.apache.fop.area.RenderPagesModel.checkPreparedPages(RenderPagesModel.java:174)
	at org.apache.fop.area.RenderPagesModel.addPage(RenderPagesModel.java:146)
```

**Comment by Intelligent2013** [comment]
Issue occurs in the module `src/main/java/org/apache/fop/render/intermediate/IFSerializer.java`
in `link.getAction().getStructureTreeElement()`:
```java
public void renderLink(Link link) throws IFException {
        noteAction(link.getAction());

        AttributesImpl atts = new AttributesImpl();
        atts.addAttribute("", "rect", "rect",
                XMLConstants.CDATA, IFUtil.toString(link.getTargetRect()));
        if (getUserAgent().isAccessibilityEnabled()) {
            addStructRefAttribute(atts,
                    ((IFStructureTreeElement) link.getAction().getStructureTreeElement()).getId());
```

`link.getAction().getStructureTreeElement()` returns `null` for one embedded math:
![image](https://user-images.githubusercontent.com/5559926/206903403-7a16b24d-0bb8-4f4d-8476-13e1a31fe212.png)

This embedded math renders in the page header (section's title renders in page headers for BIPM documents):
```xml
<fo:static-content role="artifact" flow-name="header-odd">
	<fo:block-container padding-top="12.5mm" font-size="8pt" font-family="Arial">
		<fo:block text-align="right">From <fo:inline font-family="STIX Two Math">
				<fo:inline font-weight="normal" font-style="normal" font-size="1.114pt" color="white">​</fo:inline>
				<fo:basic-link fox:alt-text="4.2 ⁢ K" external-destination="url(embedded-file:math_3.2.1._00114.mml)">
					<fo:instream-foreign-object fox:alt-text="4.2 ⁢ K" fox:actual-text="&lt;math xmlns=&quot;http://www.w3.org/1998/Math/MathML&quot;&gt;&lt;mn&gt;4.2&lt;/mn&gt;&lt;mo rspace=&quot;thickmathspace&quot;&gt;⁢&lt;/mo&gt;&lt;mrow xref=&quot;U_NISTu5&quot;&gt;&lt;mi mathvariant=&quot;normal&quot;&gt;K&lt;/mi&gt;&lt;/mrow&gt;&lt;/math&gt;">
						<math xmlns="http://www.w3.org/1998/Math/MathML">
							<mathml:mstyle scriptminsize="6pt">
								<mn>4.2</mn>
								<mo rspace="thickmathspace">⁢</mo>
								<mrow xref="U_NISTu5">
									<mi mathvariant="normal">K</mi>
								</mrow>
							</mathml:mstyle>
						</math>
					</fo:instream-foreign-object>
				</fo:basic-link>
			</fo:inline> to the triple point of neo
```

but looks like Apache FOP can't properly process link from the page header to the embedded file, because header marks as`role="artifact"`, i.e. the content of header is out of the PDF StructureTree, therefore we get `null` for `link.getAction().getStructureTreeElement()`.
I'll try omit link from math in the header to the embedded .mml.

**Comment by Intelligent2013** [comment]
Fixed.
