### ISSUE TITLE
Auto-detect for fonts?

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-native-pdf#52]
According to https://xmlgraphics.apache.org/fop/2.4/fonts.html the fonts can be auto-detected. If so, we don't need to manually refer to fonts?

**Comment by ronaldtse** [comment]
Run into this problem after enabling `<auto-detect/>`:

```
org.apache.fop.pdf.PDFConformanceException: For PDF/UA-1, all fonts, even the base 14 fonts, have to be embedded! Offending font: /Courier
	at org.apache.fop.pdf.PDFFont.validate(PDFFont.java:172)
	at org.apache.fop.pdf.PDFFont.output(PDFFont.java:179)
	at org.apache.fop.pdf.PDFDocument.outputIndirectObject(PDFDocument.java:1055)
	at org.apache.fop.pdf.PDFDocument.streamIndirectObject(PDFDocument.java:1020)
	at org.apache.fop.pdf.PDFLinearization.writePage1(PDFLinearization.java:378)
	at org.apache.fop.pdf.PDFLinearization.writeObjects(PDFLinearization.java:320)
	at org.apache.fop.pdf.PDFLinearization.outputPages(PDFLinearization.java:269)
	at org.apache.fop.render.pdf.PDFContentGenerator.flushPDFDoc(PDFContentGenerator.java:153)
	at org.apache.fop.render.pdf.PDFDocumentHandler.endDocument(PDFDocumentHandler.java:189)
	at org.apache.fop.render.intermediate.util.IFDocumentHandlerProxy.endDocument(IFDocumentHandlerProxy.java:187)
	at org.apache.fop.render.intermediate.IFRenderer.stopRenderer(IFRenderer.java:295)
	at org.apache.fop.area.RenderPagesModel.endDocument(RenderPagesModel.java:265)
	at org.apache.fop.area.AreaTreeHandler.endDocument(AreaTreeHandler.java:342)
	at org.apache.fop.fo.DelegatingFOEventHandler.endDocument(DelegatingFOEventHandler.java:94)
	at org.apache.fop.accessibility.fo.FO2StructureTreeConverter.endDocument(FO2StructureTreeConverter.java:124)
	at org.apache.fop.fo.FOTreeBuilder.endDocument(FOTreeBuilder.java:170)
	at org.apache.xalan.transformer.TransformerIdentityImpl.endDocument(TransformerIdentityImpl.java:963)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endDocument(AbstractSAXParser.java:746)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:546)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:888)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1216)
	at org.apache.xalan.transformer.TransformerIdentityImpl.transform(TransformerIdentityImpl.java:485)
	at com.metanorma.fop.mn2pdf.convertmn2pdf(mn2pdf.java:93)
	at com.metanorma.fop.mn2pdf.main(mn2pdf.java:148)
```

This SO post indicates that it might be resolvable:
https://stackoverflow.com/questions/38429504/pdf-ua-1-all-fonts-even-the-base-14-fonts-have-to-embedded-error

**Comment by Intelligent2013** [comment]
We need to manually refer to fonts. There are two reasons for it:
- if set auto-detect, then FOP will find fonts in OS fonts system path, i.e. we have to copy custom fonts (like SimSun) into OS system font folder,
- for PDF/UA conformance, it's necessary to set embed-url attribute for font embedding.

**Comment by Intelligent2013** [comment]
This issue was solved here:
- [Degrade gracefully if fonts not found](https://github.com/metanorma/mn-native-pdf/issues/74)
and  
- [Move MN_PDF_FONT_PATH environment variable inside mn2pdf Java code](https://github.com/metanorma/mn2pdf/issues/8)

**Comment by ronaldtse** [comment]
This is well done, thank you @Intelligent2013 !
