### ISSUE TITLE
Wrong baseline for glyphs from Noto Emoji font 

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/mn-native-pdf#672]
Source issue: https://github.com/metanorma/metanorma-ogc/issues/655

The source text:
```
✔️ (U+2714)
❌ (U+274C)
⚪️ (U+26AA)
⭕️ (U+26AB)
⚠️ (U+26A0)
```

The source test adoc fragment:
```
...
:fonts: Noto Emoji

== Scope

&#x2714; (U+2714)
                  
&#x274C; (U+274C)
                  
&#x26AA; (U+26AA)
                  
&#x2B55; (U+26AB)
                  
&#x26A0; (U+26A0)
```

The Presentation XML:
```xml
<p id="_">✔ (U+2714)</p>

<p id="_">❌ (U+274C)</p>

<p id="_">⚪ (U+26AA)</p>

<p id="_">⭕ (U+26AB)</p>

<p id="_">⚠ (U+26A0)</p>
```

PDF rendering issue - emoji glyphs shifted up:
![image](https://github.com/metanorma/mn-native-pdf/assets/5559926/9d9c48b9-1f4e-4b4d-abab-891583cecf20)

**Comment by Intelligent2013** [comment]
If specify the font explicitly:
```adoc
[css font-family:"Noto Emoji"]#&#x2714;# (U+2714)

[css font-family:"Noto Emoji"]#&#x274C;# (U+274C)

[css font-family:"Noto Emoji"]#&#x26AA;# (U+26AA)

[css font-family:"Noto Emoji"]#&#x2B55;# (U+26AB)

[css font-family:"Noto Emoji"]#&#x26A0;# (U+26A0)
```

the presentation XML:
```xml
<p id="_"><span style="font-family:&quot;Noto Emoji&quot;">✔</span> (U+2714)</p>

<p id="_"><span style="font-family:&quot;Noto Emoji&quot;">❌</span> (U+274C)</p>

<p id="_"><span style="font-family:&quot;Noto Emoji&quot;">⚪</span> (U+26AA)</p>

<p id="_"><span style="font-family:&quot;Noto Emoji&quot;">⭕</span> (U+26AB)</p>

<p id="_"><span style="font-family:&quot;Noto Emoji&quot;">⚠</span> (U+26A0)</p>
```

the PDF renders correctly:
![image](https://github.com/metanorma/mn-native-pdf/assets/5559926/eda94df1-ee9a-492f-9178-6d285e251c55)

So this is Apache FOP fallback fonts substitution issue. I'll create a ticket on the Apache FOP tracker.

**Comment by Intelligent2013** [comment]
Issue added: https://issues.apache.org/jira/browse/FOP-3175

**Comment by Intelligent2013** [comment]
I've found the workaround solution. Need enclose each emoji char into `<fo:character character="..."/>`. I'll add into XSLT.

**Comment by Intelligent2013** [comment]
Actually it's not emoji chars. The chars from the Unicode ranges:

- Miscellaneous Symbols https://www.compart.com/en/unicode/block/U+2600:   U+2600 - U+26FF 
- Dingbats https://www.compart.com/en/unicode/block/U+2700:  U+2700 - U+27BF
- Miscellaneous Symbols and Arrows https://www.compart.com/en/unicode/block/U+2b55: U+2B00 - U+2BFF

To prevent the wrong rendering of chars from the another ranges, I'll include from U+25A0 to U+2BFF:
(from https://www.compart.com/en/unicode/block)
- U+25A0 - U+25FF	Geometric Shapes
- U+2600 - U+26FF	Miscellaneous Symbols
- U+2700 - U+27BF	Dingbats
- U+27C0 - U+27EF	Miscellaneous Mathematical Symbols-A
- U+27F0 - U+27FF	Supplemental Arrows-A
- U+2800 - U+28FF	Braille Patterns
- U+2900 - U+297F	Supplemental Arrows-B
- U+2980 - U+29FF	Miscellaneous Mathematical Symbols-B
- U+2A00 - U+2AFF	Supplemental Mathematical Operators
- U+2B00 - U+2BFF	Miscellaneous Symbols and Arrows

**Comment by Intelligent2013** [comment]
There is one char (📝) from range:
- U+1F300 - U+1F5FF	Miscellaneous Symbols and Pictographs

**Comment by Intelligent2013** [comment]
Apache FOP doesn't support surrogate chars in `fo:character`, i.e. for `<fo:charactercharacter="📝"/>` the exception occurs:
```
isolated high surrogate
java.lang.IllegalArgumentException: isolated high surrogate
	at org.apache.fop.complexscripts.bidi.UnicodeBidiAlgorithm.convertToScalar(UnicodeBidiAlgorithm.java:660)
	at org.apache.fop.complexscripts.bidi.UnicodeBidiAlgorithm.resolveLevels(UnicodeBidiAlgorithm.java:59)
	at org.apache.fop.complexscripts.bidi.DelimitedTextRange.resolve(DelimitedTextRange.java:130)
	at org.apache.fop.complexscripts.bidi.DelimitedTextRange.resolve(DelimitedTextRange.java:108)
	at org.apache.fop.complexscripts.bidi.BidiResolver.resolveInlineDirectionality(BidiResolver.java:123)
	at org.apache.fop.complexscripts.bidi.BidiResolver.resolveInlineDirectionality(BidiResolver.java:70)
	at org.apache.fop.layoutmgr.PageSequenceLayoutManager.activateLayout(PageSequenceLayoutManager.java:110)
	at org.apache.fop.area.AreaTreeHandler.endPageSequence(AreaTreeHandler.java:267)
	at org.apache.fop.fo.DelegatingFOEventHandler.endPageSequence(DelegatingFOEventHandler.java:114)
	at org.apache.fop.accessibility.fo.FO2StructureTreeConverter.endPageSequence(FO2StructureTreeConverter.java:184)
	at org.apache.fop.fo.pagination.PageSequence.endOfNode(PageSequence.java:140)
	at org.apache.fop.fo.FOTreeBuilder$MainFOHandler.endElement(FOTreeBuilder.java:390)
	at org.apache.fop.fo.FOTreeBuilder$3.run(FOTreeBuilder.java:207)
```

It would be better to replace
- ✍(U+270D)
Noto Emoji font: ![image](https://github.com/metanorma/mn-native-pdf/assets/5559926/c46cb6a5-035a-4599-9d9f-19b7216eac86)
- or ✏(U+270F).
Noto Emoji font:  ![image](https://github.com/metanorma/mn-native-pdf/assets/5559926/fdfe467b-425d-4bf6-bae8-958d4854e293)
