### ISSUE TITLE
Unable to compile XSLTs on macOS

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-native-pdf#82]
I'm getting this error on running `make`:

```sh
make 
XSLT_PATH_CORE=xslt_src/iec.international-standard.core.xsl; \
	XSLT_PATH_MERGE=xslt_src/merge.xsl; \
	java -jar xalan/xalan.jar -IN $XSLT_PATH_CORE -XSL $XSLT_PATH_MERGE -OUT xslt/iec.international-standard.xsl

(Location of error unknown)XSLT Error (java.lang.NoClassDefFoundError): org/apache/xml/serializer/SerializerTrace
Exception in thread "main" java.lang.RuntimeException: org/apache/xml/serializer/SerializerTrace
	at org.apache.xalan.xslt.Process.doExit(Process.java:1155)
	at org.apache.xalan.xslt.Process.main(Process.java:1128)
make: *** [xslt/iec.international-standard.xsl] Error 1
```

@Intelligent2013 would you have idea why? I've tried OpenJDK 8 and also 13, but the error is still the same. Thanks!

**Comment by ronaldtse** [comment]
Ah, I removed `xalan/` directory and re-downloaded -- works. Thanks!
