### ISSUE TITLE
Error in loading embedded fonts?

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-native-pdf#87]
I'm getting this. Is this normal?

```
make documents/itu-G.191.pdf
cp mn-samples-itu/documents/G.191.xml sources/itu-G.191.xml
FILENAME=sources/itu-G.191.xml; \
	OUTFILE=documents/itu-G.191.pdf; \
	MN_FLAVOR=$(xmllint --xpath 'name(*)' ${FILENAME} | cut -d '-' -f 1); \
	DOCTYPE=$(xmllint --xpath "//*[local-name()='doctype']/text()" ${FILENAME}); \
	XSLT_PATH=/Users/me/src/mn/mn-native-pdf/xslt/${MN_FLAVOR}.${DOCTYPE}.xsl; \
  java -jar mn2pdf.jar /fonts $FILENAME $XSLT_PATH $OUTFILE
mn2pdf

Preparing...
Input: Fonts path (/fonts)
Input: XML (sources/itu-G.191.xml)
Input: XSL (/Users/me/src/mn/mn-native-pdf/xslt/itu.recommendation.xsl)
Output: PDF (documents/itu-G.191.pdf)

Transforming...
file:/Users/me/src/mn/mn-native-pdf/xslt/itu.recommendation.xsl; Line #63; Column #16; INFO: Document namespace: 'https://www.metanorma.org/ns/itu'
java.nio.file.NoSuchFileException: /fonts/SourceSansPro-Regular.ttf
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:434)
	at java.nio.file.Files.newOutputStream(Files.java:216)
	at java.nio.file.Files.copy(Files.java:3016)
	at com.metanorma.fop.fontConfig.prepareFonts(fontConfig.java:91)
	at com.metanorma.fop.fontConfig.<init>(fontConfig.java:69)
	at com.metanorma.fop.mn2pdf.convertmn2pdf(mn2pdf.java:77)
	at com.metanorma.fop.mn2pdf.main(mn2pdf.java:156)
make: *** [documents/itu-G.191.pdf] Error 255
rm sources/itu-G.191.xml
```

**Comment by ronaldtse** [comment]
From @Intelligent2013 
> fonts are embedded into JAR, but they copying into the fonts folder on start, because we need physical file on the disk to embed it. All fonts from .JAR file copying into the folder that passed as 1st param:
> java -jar mn2pdf.jar ${MN_PDF_FONT_PATH} $$FILENAME $$XSLT_PATH $$OUTFILE
> In this case - ${MN_PDF_FONT_PATH}

Got it, so if `MN_PDF_FONT_PATH` is not set the fonts cannot be read from the right path. Thanks.
